name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  cvmfs-centos7:
    # Run on GitHub Hosted Linux so we have Docker
    runs-on: [ubuntu-latest]
    steps:
      # Install and start CVMFS, possible place for action-ization ('setup-cvmfs') 
      - name: Install and Start CVMFS
        run: |
          sudo apt-get install lsb-release
          wget https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/cvmfs-release-latest_all.deb
          sudo dpkg -i cvmfs-release-latest_all.deb
          rm -f cvmfs-release-latest_all.deb
          sudo apt-get update
          sudo apt-get install cvmfs cvmfs-config-default
          sudo cvmfs_config setup
          echo  "CVMFS_REPOSITORIES=sft.cern.ch" | sudo tee -a  /etc/cvmfs/default.local > /dev/null
          echo  "CVMFS_HTTP_PROXY=DIRECT"  | sudo tee -a  /etc/cvmfs/default.local > /dev/null
          sudo service autofs restart
          sudo cvmfs_config probe
      # Like Azure, if we have to run steps mixed between VM and Container, Container must be manually managed
      - name: Pull Docker Image
        run: docker pull benmorgan/lcg-builder
      - name: Create Docker Container
        run: docker run -itd --name builder -v $GITHUB_WORKSPACE:/workspace -v /cvmfs:/cvmfs -w /workspace benmorgan/lcg-builder
      # Now the actual builds...
      - uses: actions/checkout@v2
      # Run each config in series just to check that things work
      - name: Build CentOS/gcc9 (LCG_97python3)
        env:
          BUILD_DIR: build-gcc8
          LCG_RELEASE: /cvmfs/sft.cern.ch/lcg/views/LCG_97python3/x86_64-centos7-gcc9-opt
        run:
          docker exec builder bash -c "mkdir $BUILD_DIR"
          docker exec builder bash -c ". $LCG_RELEASE/setup.sh && cd $BUILD_DIR && cmake .. && cmake --build . && ctest"
